### DISCUSSION TITLE
How to animate changes in grid layout without fixed size

### DISCUSSION THREAD

**Discussion by skorphil** [motiondivision/motion#2506] [Q&A]
Hi, is it possible to animate grid-layout changes without specifying fixed size to grid items? 
I'm trying to animate the change in the grid from `collapsed` to `expanded`
```css
.expanded {
    height: auto;
    grid-template-columns: 1fr 1fr;
  }
  
  .collapsed {
    height: 40px;
    grid-template-rows: 1fr;
    grid-template-columns: repeat(auto-fit, minmax(100px, 1fr));
  }
```

However, i got unwanted distortions on grid items. The only way i managed to get rid of distortions is to specify sizes of grid item:
```css
.fixed-size {
    width: 140px;
    height: 20px;
    background-color: grey;
  }
```

you can play with this demo here: https://codesandbox.io/p/devbox/qm3ts4

Any way to fix this without specifying fixed sizes?

https://github.com/framer/motion/assets/6762009/18d6ae5c-d63c-41d8-aa4a-bfc00ed82576
