### ISSUE TITLE
[FEATURE] rangeStart and the rangeEnd support

### ISSUE THREAD

**Issue by istarkov** [motiondivision/motion#3001]
**Is your feature request related to a problem? Please describe.**

### Issue: Need for `rangeStart`/`rangeEnd` Attributes Despite `offset`

The CSS attributes [`animation-range-end`](https://developer.mozilla.org/en-US/docs/Web/CSS/animation-range-end) and [`animation-range-start`](https://developer.mozilla.org/en-US/docs/Web/CSS/animation-range-start) have corresponding `rangeStart`/`rangeEnd` attributes in the [Web Animations API](https://developer.mozilla.org/en-US/docs/Web/API/Element/animate#rangeend).

#### Question:
Why are `rangeStart` and `rangeEnd` needed if we already have `offset`?  

The issue arises with entry animations.

---

#### Example with Native CSS:

In this example, a `:hover` animation works after the scroll-linked animation completes:

```css
@keyframes animate-in-range {
  from {
    opacity: 0;
  }
  to {
    opacity: 1;
  }
}

.box-right {
  animation: linear animate-in-range;
  animation-timeline: scroll();
  animation-range: 0% 20%;
}

.box-right:hover {
  opacity: 0.5; /* After 20% this works!!!! */
}

/* animated element has anim.effect.getComputedTiming().progress === null */
```

When using Motion Dev, the behavior is different:

```javascript
const animation = animate(
  box,
  {
    opacity: [0, 1],
  },
  {
  }
);

const scrollAnimation = scroll(animation, { offset: ['0%', '20%'] });

// animated element has anim.effect.getComputedTiming().progress === 1 even after 20%
```

With native CSS, the animation’s progress is null after the defined range. 
However, when using Motion Dev, the animation’s progress remains 1 even after the range (e.g., 20%). 
This creates a discrepancy in expected behavior, especially for entry animations like :hover.

**Describe the solution you'd like**

Support for the corresponding `rangeStart`/`rangeEnd` attributes in the [Web Animations API](https://developer.mozilla.org/en-US/docs/Web/API/Element/animate#rangeend).
